# -*- coding: utf-8 -*-
"""Salinan dari modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Guilc1m8FjWOZ4qNusKwjEQjeD4vzSbk
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# LOAD DATASET
import pandas as pd

url = 'https://media.githubusercontent.com/media/RahmatTM/Workflow-CI/refs/heads/main/MLProject/dataset_preprocessing/data_clean.csv'

# MENENTUKAN FEATURE DAN TARGET
import pandas as pd # Ensure pandas is imported for pd.read_csv
df = pd.read_csv(url) # Load the DataFrame using the 'url' defined in the previous cell
target_column = 'price_category'

X = df.drop(columns=[target_column])
y = df[target_column]

# SPLIT DATA
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# TRAIN MODEL
model = LogisticRegression()

model.fit(X_train, y_train)

# PREDIKSI
y_pred = model.predict(X_test)

# EVALUASI
accuracy = accuracy_score(y_test, y_pred)

print(f'Akurasi: {accuracy}')

print('\nClassification Report')
print(classification_report(y_test, y_pred))
